### PR TITLE
For #35260: Refactoring scoping of sgtimezone 

### PR DESCRIPTION
**Pull request by neilvictorgrey**
so that dates are pickle-able and convertable using strftime.

### CODE REVIEW

**Comment by pboucher** [comment]
LGTM. Let's see what Travis says.

**Comment by neilvictorgrey** [comment]
Looks like Travis passes :).

**Comment by manneohrstrom** [comment]
Great! I always really disliked this and tried several times in the past to get sg dev cycles to refactor it. Super excited to see that it's being addressed! :)

We should make sure to run this through a toolkit regression test - the Shotgun model handles lots of serialized sg queries so it's a good test case.

Also some docstrings and comments would be nice! ;-)

**Comment by neilvictorgrey** [comment]
@manneohrstrom sounds good to me:
> I'll put docstrings/comments together
> Never run through toolkit regression tests; mind pinging me when you've got time and we'll run through what the process is there?

**Comment by manneohrstrom** [comment]
Sweet! By regression testing I mean a QA regression pass, e.g. we should get @mathurf to take a look :)

**Comment by neilvictorgrey** [comment]
Cool, @mathurf let me know anything you need from me to test this out.

**Comment by neilvictorgrey** [comment]
@pboucher @manneohrstrom added 2 class methods to SgTimezone to deal with backwards compatibility issues brought up by @mathurf.  Also added a bunch of docstrings.

@mathurf this update should address at least the first issue you ran into with workfiles2. I'm not sure about the second issue as there wasn't any traceback. Would you mind pulling down the latest and giving a fresh run through? Thanks! :D

**Pull request merged**
