### PR TITLE
[duguids] SG-29350 adding video to installation doc

### PR DESCRIPTION
**Pull request by shaynacohen**

### CODE REVIEW

**Comment by shaynacohen** [comment]
Also including @julien-lang on this request. I'm not sure the process for previewing/publishing is, but I would love to incorporate this update since our intern made a great video about getting started with the Python API.

**Review by 000paradox000 — APPROVED** [review]
LGTM

**Review by NorberMV — COMMENTED** [review]
Screen Shot 2022-12-12 at 3 29 07 PM
Hi Shayna, I just generated a  preview with your changes, but only the url of the video is visible, this documentation is generated using sphinx, not sure if maybe the way of embedding a video is different here.

**Comment by shaynacohen** [comment]
Thanks @NorberMV and @julien-lang ! I'll dig into both of these...

**Comment by shaynacohen** [comment]
OK @NorberMV , how does this work with html? I'm also trying to add a note box and hyperlink on the installation page.

**Comment by NorberMV** [comment]
> OK @NorberMV , how does this work with html? I'm also trying to add a note box and hyperlink on the installation page.

Screen Shot 2022-12-12 at 4 25 01 PM
Now it looks pretty good!

**Comment by NorberMV** [comment]
Screen Shot 2022-12-12 at 4 44 36 PM

Now the hyperlink is working !

**Review by NorberMV — APPROVED** [review]
The preview looks good now!

**Pull request merged**
