### PR TITLE
Add support for external SSL certificates in upload methods.

### PR DESCRIPTION
**Pull request by mike1158**
Note: Have tested that this works at our local site, but haven't
      tested it with proxy connections.

### CODE REVIEW

**Comment by cgdougm** [comment]
I don't think the ci failed due to a problem with Mike's code; it's this:
    ```AuthenticationFault: Can't authenticate script 'travis-ci'```
Can you please look into this again? Thanks

**Comment by mike1158** [comment]
Yeah, I just closed and re-opened this PR to trigger retrying the CI test.  It still failed, but it doesn't look at all related to the PR.

**Comment by jfboismenu** [comment]
Hey Mike, could you update with master, we just fixed our ci build.

**Comment by mike1158** [comment]
Closing due to CI failures. Will re-create.

**Pull request closed without merging**
