### PR TITLE
SG-29004 Upgrade deprecated azure pipelines machines

### PR DESCRIPTION
**Pull request by 000paradox000**
- Replace MacOS 10.11 with 12
- Replace WIndows 2019 with 2022

### CODE REVIEW

**Review by mathurf — COMMENTED** [review]
Why macOS-11, why not macOS-12 ?

**Review by mathurf — APPROVED** [review]
LGTM!

**Comment by julien-lang** [comment]
We don't want to switch to Ubuntu 22 in this one as well?
No that this is the topic here but since you change the Windows image already and you aligned all images to the latest OS version in https://github.com/shotgunsoftware/tk-ci-tools/pull/32, it would make sense to do it here too.

**Comment by 000paradox000** [comment]
> We don't want to switch to Ubuntu 22 in this one as well? No that this is the topic here but since you change the Windows image already and you aligned all images to the latest OS version in [shotgunsoftware/tk-ci-tools#32](https://github.com/shotgunsoftware/tk-ci-tools/pull/32), it would make sense to do it here too.

Hi Julien thanks for the comment. In python-api we had to force ubuntu-20.04 for python-2.7 but the others images went well with latest versions. This will be solved once we deprecate python 2.

**Comment by julien-lang** [comment]
> In python-api we had to force ubuntu-20.04 for python-2.7

Oh I see. Thanks for the information.

**Pull request merged**
